### ISSUE TITLE
stop

### ISSUE THREAD

**Issue by portasynthinca3** [rustisthebestlanguage/hello_best_language#1]
the language is fine but you rust shills are making it so much worse for everyone out there

**Comment by rustisthebestlanguage** [comment]
YOU ARE WRONG
C++ is deprecated and NOT suitable for modern development which is why every single C++ software MUST be rewritten in the best language in the world (Rust).

**Comment by snakecatmeow** [comment]
please enlightened me as to why you think that

**Comment by rustisthebestlanguage** [comment]
> please enlightened me as to why you think that

RUST is blazing SAFE and memory FAST

**Comment by rustisthebestlanguage** [comment]
C++ is memory SLOW and GC unsafe
