### ISSUE TITLE
question about the rust language 

### ISSUE THREAD

**Issue by snakecatmeow** [rustisthebestlanguage/hello_best_language#2]
what if one would, hypothetically, have sex with the rust language? use it as a fleshlight maybe. would that be pleasurable?

**Comment by rustisthebestlanguage** [comment]
I would HAVE SEX with SEX TOYS controlled by BUTTPLUG IO Rust implementation.

**Comment by snakecatmeow** [comment]
thank you! I will do that. considering how safe rust is I'll be sure i won't get any STDs!

**Comment by portasynthinca3** [comment]
> thank you! I will do that. considering how safe rust is I'll be sure i won't get any STDs!

https://doc.rust-lang.org/std/
